module.exports={
 project:{id:'e2e-minimum'},
 chapters:[{id:'CH001',name:'平原の章',sections:[{id:'SEC001',name:'旅立ち',scenes:[{id:'SCN001',name:'王子の入隊',text:'日本語・改行\n記号「」を保持'}]}]}],
 quests:[{id:'MQ001',type:'main',name:'最初の依頼',monster_id:'MON001'}],
 events:[{id:'EV001',name:'入隊イベント',flag_id:'FLG001'}],flags:[{id:'FLG001',name:'入隊済み',default:false}],
 ai_templates:[{id:'AIT001',name:'基本AI'}],
 masters:{
  jobs:[{id:'JOB001',name:'騎士',str:11,vit:13}],status_effects:[{id:'ST001',name:'毒'}],
  skills:[{id:'SK001',name:'斬撃',power:100}],equipment:[{id:'EQ001',name:'鉄の剣',mod_ids:['MOD001']}],
  mods:[{id:'MOD001',name:'攻撃上昇',tags:['equipment']},{id:'MMOD001',name:'凶暴化',tags:['monster']},{id:'SMOD001',name:'石板強化',tags:['stone']}],
  monsters:[{id:'MON001',name:'スライム'}],tablets:[{id:'STONE001',name:'試作石板'}],
  ai_conditions:[{id:'AIC001',name:'敵がいる'}],ai_targets:[{id:'AITG001',name:'敵HP最小'}],ai_actions:[{id:'AIA001',name:'通常攻撃'}]
 },
 balance:{agi_threshold:100},drop_tables:[{id:'DROP001',equipment_id:'EQ001'}],game_settings:{party_size:6}
};
