const fs=require('fs'),vm=require('vm'),assert=require('assert');
const registry=require('../assets/shared/config/skill-registry.json');
const nativeCompiler=require('../assets/shared/js/skill-compiler.js');
const budgetRules=require('../assets/shared/config/skill-budget-rules.json');
const src=fs.readFileSync('studio/skill/skill-generator.js','utf8');
const document={readyState:'loading',addEventListener(){},getElementById(){return null},querySelector(){return null},dispatchEvent(){}};
const ctx={window:null,document,console,setTimeout,clearTimeout,AbortController,CustomEvent:function(){}};ctx.window=ctx;
ctx.GKSGenericSkillAuthoringRegistry={buildUiDefinition:()=>({})};
ctx.GKSGenericSkillBudgetEngine={calculate:(skill,rules)=>({ok:true,budgetRuleVersion:rules.budgetRuleVersion,cost:10,limit:20,errors:[],calculationTrace:[]})};
ctx.GKSSkillCompileService={compileSkill:async(skill,{registry})=>nativeCompiler.compileSkill(skill,registry)};
ctx.fetch=async url=>({ok:true,status:200,json:async()=>String(url).includes('budget')?budgetRules:registry});
vm.createContext(ctx);vm.runInContext(src,ctx);
const api=ctx.GKSSkillGenerator;
(async()=>{
 assert.ok(api.g06StrictSkillIssues&&api.g06RevalidateGenericBatch,'G06 stage2 API missing');
 await api.loadGenericDefinition(); await api.loadBudgetRules();
 const clean={schemaVersion:1,id:'S1',name:'Skill',skillLevel:1,trigger:{type:'ON_USE',scope:'SELF'},conditions:[],target:{side:'ENEMY',range:'SINGLE'},effects:[{type:'DAMAGE',power:10}],resource:{mpCost:0,cooldown:0,activationPriority:0}};
 assert.strictEqual(api.g06StrictSkillIssues(clean,0).length,0,'known Generic Skill fields should pass strict shape');
 const bad={...clean,unexpected:1};
 assert.ok(api.g06StrictSkillIssues(bad,0).some(x=>x.code==='G06_UNKNOWN_FIELD'&&x.path==='skills[0].skill.unexpected'),'unknown top-level field must be rejected');
 const badNested={...clean,target:{...clean.target,mystery:true}};
 assert.ok(api.g06StrictSkillIssues(badNested,0).some(x=>x.code==='G06_UNKNOWN_FIELD'&&x.path.endsWith('.target.mystery')),'unknown nested field must be rejected');
 assert.throws(()=>api.g06ImportJsonObject({schema:'GKS_GENERIC_SKILL_BATCH',version:'9',skills:[]},'GKS_GENERIC_SKILL_BATCH'),e=>e.code==='G06_VERSION_MISMATCH');
 const batch={schema:'GKS_GENERIC_SKILL_BATCH',version:'1.0.0',sourceSchema:'GKS_GENERIC_SKILL_AI_BATCH_RESULT',aiGenerationRuleVersion:'A',budgetRuleVersion:budgetRules.budgetRuleVersion,skills:[{index:0,skill:clean,generation:{},validation:{budgetResult:{ok:true,budgetRuleVersion:budgetRules.budgetRuleVersion,cost:10,limit:20},compilerWarnings:[]}}]};
 const report=await api.g06RevalidateGenericBatch(batch);
 assert.strictEqual(report.summary.allAccepted,true);assert.strictEqual(report.entries[0].roundtripMatch,true);
 const mismatch=JSON.parse(JSON.stringify(batch));mismatch.skills[0].validation.budgetResult.cost=11;
 const mismatchReport=await api.g06RevalidateGenericBatch(mismatch);
 assert.strictEqual(mismatchReport.entries[0].status,'REJECT');
 assert.ok(mismatchReport.entries[0].issues.some(x=>x.code==='G06_ROUNDTRIP_MISMATCH'));
 const unknown=JSON.parse(JSON.stringify(batch));unknown.skills[0].skill.effects[0].mystery=1;
 const unknownReport=await api.g06RevalidateGenericBatch(unknown);
 assert.ok(unknownReport.entries[0].issues.some(x=>x.code==='G06_UNKNOWN_FIELD'));
 for(const marker of ['skgG06GenericFile','skgG06GenericJson','skgG06Revalidate','G06_ROUNDTRIP_MISMATCH','G06_UNKNOWN_FIELD'])assert.ok(src.includes(marker),`missing ${marker}`);
 console.log('PASS GKS-B541 G06 Generic Skill reimport/revalidation strict gate');
})().catch(e=>{console.error(e);process.exit(1);});
