const fs=require('fs'),vm=require('vm'),assert=require('assert');
const build=require('../package-build.json');
const registry=require('../assets/shared/config/skill-generic-registry.json');
assert.strictEqual(build.game_build,'GA-B486.121');
assert.strictEqual(build.studio_build,'GKS-B553');
const ctx={console,module:{exports:{}},globalThis:null};ctx.globalThis=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('assets/shared/js/generic-skill-authoring-registry.js','utf8'),ctx);
const author=ctx.GKSGenericSkillAuthoringRegistry;assert.ok(author);assert.ok(['G02','G03','G04','G05'].includes(author.VERSION));
assert.ok(['G02','G03','G04','G05'].includes(registry.authoring.phase));
const ui=author.buildUiDefinition(registry);
assert.ok(ui.fields&&ui.fields.power&&ui.fields.effectId&&ui.fields.lifetime,'G02 field definitions missing');
assert.deepStrictEqual(Array.from(ui.effects,x=>x.type),registry.runtime.effects,'Effect choices must be Registry-driven');
assert.strictEqual(ui.effects.find(x=>x.type==='SPECIAL').enabled,false,'SPECIAL boundary must stay disabled');
const apply=author.resolveEffectRequirements(registry,'APPLY',{effectId:'BURN'});
for(const f of ['effectId','power','duration'])assert.ok(apply.requiredFields.includes(f),`BURN field missing: ${f}`);
const cover=author.resolveEffectRequirements(registry,'TARGET_CONTROL',{lifetime:'USES'});assert.ok(cover.requiredFields.includes('uses'));
const sg=fs.readFileSync('studio/skill/skill-generator.js','utf8');
for(const marker of ['skgGenericEffects','skgGenericEffectFields','renderGenericDynamic','makeGenericField','generateGenericPreview','authoring_model:\'generic\''])assert.ok(sg.includes(marker),`G02 UI marker missing: ${marker}`);
assert.ok(sg.includes('旧Runtime互換UI'),'Legacy UI must remain compatibility-only, not deleted');
assert.ok(!sg.includes('id="skgGenericEffects">${LOGICS.map'),'Generic Effect choices must not come from legacy LOGICS');
const html=fs.readFileSync('studio/index.html','utf8');assert.ok(html.includes('generic-skill-authoring-registry.js?v=4'));assert.ok(html.includes('skill-generator.js?v=25'));
console.log('SKILL_GENERATOR_G02_EFFECT_UI_GKS_B529_PASS');
