const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('game/index.html','utf8');
const runtime=fs.readFileSync('game/assets/js/app-runtime.js','utf8');
const formalRuntime=fs.readFileSync('game/assets/js/tag-skill-runtime.js','utf8');
const harness=fs.readFileSync('assets/shared/js/device-game-test-harness.js','utf8');
const build=JSON.parse(fs.readFileSync('package-build.json','utf8'));
const buildId=build.game_build;
const cacheId=buildId.replace(/^GA-B/,'').replace('.','');
assert(html.includes('id="tagTestRunHealSingle"'),'Formal Gameに単体回復検証ボタンがありません');
assert(html.includes('id="tagTestRunHealAll"'),'Formal Gameに全体回復検証ボタンがありません');
assert(runtime.includes('function runHealSingleValidation()'),'Formal Game単体回復検証がありません');
assert(runtime.includes('function runHealAllValidation()'),'Formal Game全体回復検証がありません');
assert(runtime.includes("findSkill('SKL-TEST-HEAL-100')"),'単体回復Formal fixture接続がありません');
assert(runtime.includes("findSkill('SKL-TEST-HEAL-ALL-60')"),'全体回復Formal fixture接続がありません');
assert(runtime.includes('executeSkillRuntime(actor,target,skill)'),'単体回復がFormal Runtimeを実行していません');
assert(runtime.includes('executeSkillRuntime(actor,allies[1],skill)'),'全体回復がFormal Runtimeを実行していません');
assert(formalRuntime.includes("const GKS_SKILL_RUNTIME_MODE=Object.freeze({production:'runtimeContracts_only'})"),'Formal RuntimeがruntimeContracts-onlyではありません');
assert(!formalRuntime.includes('function compileTaggedSkill('),'Production RuntimeへTag compilerが戻っています');
assert(harness.includes("kind:'real_device_acceptance'"),'Formal Game実機JSONハーネスがありません');
assert(harness.includes('結果JSONをコピー'),'Formal Game実機JSON持ち出しがありません');
assert(html.includes(`../assets/shared/js/device-game-test-harness.js?v=${cacheId}`),'Formal Game実機ハーネスのキャッシュバスターが現行ビルドではありません');
const gameSw=fs.readFileSync('game/sw.js','utf8');
assert(gameSw.includes(`ga-game-b${cacheId}-b572`),'Game Service Workerキャッシュが現行ビルドではありません');
assert(gameSw.includes(`device-game-test-harness.js?v=${cacheId}`),'Service Workerが現行Formal実機ハーネスを参照していません');
console.log('HEAL_FORMAL_GAME_DEVICE_CURRENT_BUILD_OK');
