const fs=require('fs');
const assert=(v,m)=>{if(!v)throw new Error(m)};
const battle=fs.readFileSync('game/assets/js/battle-control.js','utf8');
const app=fs.readFileSync('game/assets/js/app-runtime.js','utf8');
const html=fs.readFileSync('game/index.html','utf8');
const config=fs.readFileSync('assets/shared/config/runtime-config.js','utf8');
assert(/processModifierStacks\(\);\s*processShieldEffects\(\);\s*processDotStacks\(\);/.test(battle),'通常Tickにシールド期限処理が接続されていません');
assert(battle.includes("clearAllShields('battle_end')"),'戦闘終了時シールド消去が接続されていません');
assert(app.includes("battle.units.filter(u=>u.side==='敵')"),'戦闘終了検証が全敵を対象にしていません');
assert(app.includes("build:'GA-B486.2'"),'ゲーム側シールドJSONのビルド番号が不一致です');
assert(app.includes('tag-shield-device-validation-GA-B486.2-'),'シールドJSONファイル名のビルド番号が不一致です');
assert(html.includes('GA-B486.2'),'ゲーム画面のビルド番号が不一致です');
assert(config.includes('gameBuild: "GA-B486.2"'),'共通設定のビルド番号が不一致です');
console.log('SHIELD_GAME_CONNECTION_GA_B486_2_OK');
