const fs=require('fs'),vm=require('vm'),assert=require('assert');
const build=require('../package-build.json');
const registry=require('../assets/shared/config/skill-generic-registry.json');
const rules=require('../assets/shared/config/skill-budget-rules.json');
assert.strictEqual(build.game_build,'GA-B486.121');
assert.strictEqual(build.studio_build,'GKS-B552');
assert.ok(['G04','G05'].includes(registry.authoring.phase));
assert.strictEqual(rules.budgetRuleVersion,'G04-BUDGET-V1');
assert.strictEqual(rules.existing_skill_policy,'NO_AUTOMATIC_RECALCULATION');
const ctx={console,module:{exports:{}},globalThis:null};ctx.globalThis=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('assets/shared/js/generic-skill-budget-engine.js','utf8'),ctx);
const engine=ctx.GKSGenericSkillBudgetEngine;assert.strictEqual(engine.VERSION,'G04');
const normal={schemaVersion:1,id:'G04-NORMAL',name:'Normal',skillLevel:10,trigger:{type:'ON_USE',scope:'SELF'},conditions:[],target:{side:'ENEMY',range:'SINGLE'},effects:[{type:'DAMAGE',power:100,damageType:'PHYSICAL'}],resource:{mpCost:0,cooldown:0,activationPriority:0}};
const ok=engine.calculate(normal,rules,registry);assert.strictEqual(ok.ok,true);assert.strictEqual(ok.withinBudget,true);assert.strictEqual(ok.manualOverrideApplied,false);assert.ok(ok.calculationTrace.some(x=>x.kind==='effect_cost'));assert.ok(ok.calculationTrace.some(x=>x.kind==='trigger'));assert.ok(ok.calculationTrace.some(x=>x.kind==='condition_refund'));assert.ok(ok.calculationTrace.some(x=>x.kind==='mp_refund'));assert.ok(ok.calculationTrace.some(x=>x.kind==='cooldown_refund'));
const apply={...normal,id:'G04-APPLY',effects:[{type:'APPLY',effectId:'STUN',duration:200}]};const applyResult=engine.calculate(apply,rules,registry);assert.strictEqual(applyResult.ok,true);const applyCost=applyResult.calculationTrace.find(x=>x.kind==='effect_cost');assert.strictEqual(applyCost.registryEffectWeight,3);
const over={...normal,id:'G04-OVER',skillLevel:1,trigger:{type:'WHILE_SOURCE_ALIVE',scope:'SELF'},target:{side:'ENEMY',range:'ALL'},effects:[{type:'DAMAGE',power:1000,damageType:'FIXED'}]};const rejected=engine.calculate(over,rules,registry);assert.strictEqual(rejected.ok,false);assert.strictEqual(rejected.withinBudget,false);assert.ok(rejected.errors.some(x=>x.startsWith('SKILL_BUDGET_EXCEEDED')),'over budget must reject');
const badOverride=engine.calculate(over,rules,registry,{manualOverride:true,overrideReason:'short'});assert.strictEqual(badOverride.ok,false);assert.strictEqual(badOverride.manualOverrideApplied,false);assert.ok(badOverride.errors.some(x=>x.includes('8文字以上')));
const acceptedOverride=engine.calculate(over,rules,registry,{manualOverride:true,overrideReason:'balance exception approved'});assert.strictEqual(acceptedOverride.ok,true);assert.strictEqual(acceptedOverride.withinBudget,false);assert.strictEqual(acceptedOverride.manualOverrideApplied,true);assert.strictEqual(acceptedOverride.manualOverrideAudit.budgetRuleVersion,'G04-BUDGET-V1');assert.ok(acceptedOverride.calculationTrace.some(x=>x.kind==='manual_override'));
const withRefunds={...normal,id:'G04-REFUND',conditions:[{scope:'SELF',property:'SELF_HP_RATE',operator:'<=',value:0.5}],resource:{mpCost:20,cooldown:300,activationPriority:0}};const refund=engine.calculate(withRefunds,rules,registry);assert.ok(refund.cost<ok.cost,'condition/mp/cooldown refunds must reduce cost');
const sg=fs.readFileSync('studio/skill/skill-generator.js','utf8');for(const marker of ['loadBudgetRules','calculateGenericBudget','skgBudgetStatus','skgBudgetOverride','budget:clone(budget)','SKILL_BUDGET_EXCEEDED','既存Skillは自動再計算しません'])assert.ok(sg.includes(marker),`G04 marker missing: ${marker}`);
const html=fs.readFileSync('studio/index.html','utf8');assert.ok(html.includes('generic-skill-budget-engine.js?v=1'));assert.ok(html.includes('generic-skill-authoring-registry.js?v=4'));assert.ok(html.includes('skill-generator.js?v=25'));
console.log('SKILL_GENERATOR_G04_BUDGET_ENGINE_GKS_B531_PASS');
