const assert=require('assert'),fs=require('fs');
const build=require('../package-build.json');
assert.strictEqual(build.studio_build,'GKS-B668');
const sg=fs.readFileSync('studio/skill/skill-generator.js','utf8');
const ui=fs.readFileSync('studio/data-exchange/data-exchange-ui.js','utf8');
const html=fs.readFileSync('studio/index.html','utf8');
assert.ok(sg.includes("await global.GKSDataExchangeUI.undoLatestSession()"),'G07 Undo must use the proven latest-session path');
assert.ok(!sg.includes('g07UndoPointerKey'),'G07 exact-session pointer must be removed by rollback');
assert.ok(!sg.includes('undoSessionById(sessionId'),'G07 exact-session Undo call must be removed by rollback');
assert.ok(ui.includes('async function undoLatestSession()'),'Data Exchange latest-session Undo must remain');
assert.ok(!ui.includes('async function undoSessionById('),'B555 exact-session Undo API must be removed by rollback');
assert.ok(html.includes('skill-generator.js?v=33'),'Skill generator rollback must cache-bust');
assert.ok(html.includes('data-exchange-ui.js?v=24'),'Data Exchange UI rollback must cache-bust');
console.log('PASS GKS-B582 G07 Undo rollback to proven latest-session path');
