const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const registry=JSON.parse(fs.readFileSync('assets/shared/config/skill-registry.json','utf8'));
const compiler=require('../assets/shared/js/skill-compiler.js');
const events=[];
const battle={tick:0,units:[],log:[],result:null,pendingResult:null};
const ctx={console,battle,queueSceneEvent:()=>{},finishIfNeeded:()=>false,recordValidationEvent:(type,payload={})=>events.push({tick:battle.tick,type,...payload})};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('game/assets/js/tag-skill-runtime.js','utf8'),ctx);
const skill={schemaVersion:1,id:'SKL-9457',name:'Formal DOT basic regression',trigger:{type:'ON_USE',scope:'SELF'},conditions:[],target:{side:'ENEMY',range:'SINGLE'},effects:[{type:'APPLY',effectId:'BURN',power:20,duration:1000,interval:100,stackGain:1}],resource:{mpCost:0,cooldown:0}};
const out=compiler.compileSkill(skill,registry);assert.strictEqual(out.ok,true,JSON.stringify(out.errors));
const compiled=ctx.compileSkillForRuntime(out.compiledSkill);assert.strictEqual(compiled.ok,true,JSON.stringify(compiled.errors));
assert.ok(compiled.definition.runtimeContracts,'runtimeContracts missing');assert.ok(compiled.definition.logicOrder.includes('DOT'),'DOT logic missing');
const source={id:'A',name:'Actor',side:'ally',alive:true,damageDealt:0};
const target={id:'E',name:'Enemy',side:'enemy',alive:true,hp:5000,maxHp:5000,damageTaken:0,dotStacks:[],statusEffects:[],modifierStacks:[],shieldEffects:[],coverEffects:[]};battle.units=[source,target];
const applied=ctx.applyTaggedApplyRuntime(source,target,compiled,'DOT');assert.strictEqual(applied.result.ok,true);assert.strictEqual(applied.result.added,1);assert.strictEqual(target.dotStacks.length,1);
for(let tick=100;tick<=1000;tick+=100){battle.tick=tick;ctx.processDotStacks();}
assert.strictEqual(target.hp,4800,'DOT total damage mismatch');assert.strictEqual(target.dotStacks.length,0,'DOT stack did not expire');
assert.strictEqual(events.filter(x=>x.type==='dot_stack_added').length,1,'dot_stack_added event mismatch');assert.strictEqual(events.filter(x=>x.type==='dot_damage').length,10,'dot_damage event mismatch');assert.strictEqual(events.filter(x=>x.type==='dot_expired').length,1,'dot_expired event mismatch');
console.log('FORMAL_DOT_BASIC_GA_B457_PASS');
