'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const src=fs.readFileSync(path.join(root,'game/assets/js/studio-skill-bridge.js'),'utf8');
assert(src.includes("runtime_contract_source:runtimeContractSource"),'per-case runtime_contract_source missing');
assert(src.includes("runtime_contracts_count:runtimeContractsCount"),'runtimeContracts summary count missing');
assert(src.includes("generic_fallback_count:genericFallbackCount"),'Generic fallback summary count missing');
assert(src.includes("no_contract_count:noContractCount"),'no-contract summary count missing');
assert(src.includes("runtimeContractSource!=='runtimeContracts'"),'formal-only R06 gate missing');
assert(src.includes("R06正式Runtime契約のruntimeContracts接続が全件ではありません"),'48/48 source gate missing');
console.log('PASS test_r06_runtime_contract_source_probe_gks_b555');
