const fs=require('fs');
const assert=(v,m)=>{if(!v)throw new Error(m)};
const app=fs.readFileSync('game/assets/js/app-runtime.js','utf8');
const runtime=fs.readFileSync('game/assets/js/tag-skill-runtime.js','utf8');
const html=fs.readFileSync('game/index.html','utf8');
const build=JSON.parse(fs.readFileSync('package-build.json','utf8'));
const buildId=build.game_build;
assert(html.includes('tagTestRunShieldJson'),'Formal GameにシールドJSONボタンなし');
assert(app.includes("test:{id:'TAG-SHIELD-DEVICE-001'"),'テストIDなし');
for(const id of ['SHIELD-ABSORB-PARTIAL','SHIELD-OVERFLOW','SHIELD-INVALID-DATA-REJECT','SHIELD-DEAD-REJECT','SHIELD-ALL','SHIELD-MULTIPLE-FIFO','SHIELD-DURATION-EXPIRE','SHIELD-BATTLE-END-CLEAR'])assert(app.includes(`'${id}'`),`${id}なし`);
for(const token of ['applyTaggedShield','consumeShieldDamage','processShieldEffects','clearAllShields'])assert(runtime.includes(token),`${token}なし`);
assert(runtime.includes('runtimeContractsが必要です'),'Formal runtimeContracts必須境界なし');
assert(runtime.includes("logic==='SHIELD'"),'Formal SHIELD apply contract解決なし');
assert(app.includes('tag-shield-device-validation-'),'シールドJSONファイル名なし');
assert(app.includes("entrypoint:'game/index.html'"),'Formal Game entrypointではありません');
assert(html.includes(buildId),'Game検証画面に現行ビルド表記なし');
console.log('SHIELD_DEVICE_JSON_FORMAL_GAME_CURRENT_BUILD_OK');
