const assert=require('assert'),fs=require('fs'),vm=require('vm');
const payload=JSON.parse(fs.readFileSync('Export/skill/skills.json','utf8'));
const rows=Array.isArray(payload)?payload:payload.data;
const row=rows.find(x=>x.id==='COVER-VALIDATION-MIXED-ATTACK');
assert.ok(row,'mixed COVER validation row missing');
assert.strictEqual(row.environment,'validation');
assert.strictEqual(row.expected_result,'accepted');
assert.ok(/複合を許可/.test(row.description||''));
const ctx={console,window:{GA_PROJECT_CONFIG:{skillExportUrl:'x'}},TAG_SKILLS:[],findTagSkill:()=>null,compileTaggedSkill:null};ctx.globalThis=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('game/assets/js/tag-skill-runtime.js','utf8'),ctx);
const compiled=ctx.compileTaggedSkill(row);
assert.strictEqual(compiled.ok,true,compiled.errors.join(' / '));
const bridge=fs.readFileSync('game/assets/js/studio-skill-bridge.js','utf8');
assert.ok(bridge.includes("expected_result:record.expected_result||null"),'bridge must preserve expected_result');
assert.ok(bridge.includes("expected==='accepted'?row.compiled_ok"),'formal validation must support accepted positive cases');
console.log('PASS GKS-B552 COVER mixed positive validation');
