const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'studio/skill/skill-generator.js'),'utf8');
const index=fs.readFileSync(path.join(root,'studio/index.html'),'utf8');
const config=fs.readFileSync(path.join(root,'assets/shared/config/runtime-config.js'),'utf8');
const registry=JSON.parse(fs.readFileSync(path.join(root,'assets/shared/config/skill-registry.json'),'utf8'));
const build=JSON.parse(fs.readFileSync(path.join(root,'package-build.json'),'utf8'));
function need(v,m){if(!v)throw new Error(m)}
need(/const VERSION='1\.\d+\.0'/.test(js),'generator version');
need(Array.isArray(registry.authoring?.condition?.required_fields),'Formal condition registry missing');
need(registry.authoring.condition.required_fields.join(',')==='scope,property,operator,value','Formal condition fields mismatch');
for(const marker of ['発動条件（任意・すべてAND）','skgFormalConditionList','addFormalConditionRow','collectFormalConditions','validateFormalConditions','GKSSkillAuthoringRegistry.validateConditionDraft'])need(js.includes(marker),`Formal condition marker missing: ${marker}`);
need(!js.includes('CONDITION_SELF_HP_RATE'),'retired tag-condition constant must be removed');
need(!js.includes('CONDITION_OPERATORS'),'retired tag-condition operators must be removed');
need(!js.includes('conditions:collectConditions()'),'retired condition collector must be removed');
need(index.includes(build.studio_build),'studio build');
need(/\.\/skill\/skill-generator\.js\?v=\d+/.test(index),'cache key');
need(config.includes(`gameBuild: "${build.game_build}"`),'game build');
need(config.includes(`studioBuild: "${build.studio_build}"`),'studio build config');
console.log('SKILL_GENERATOR_FORMAL_CONDITIONS_REGRESSION_PASS');
