const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('game-tag-test/index.html','utf8');
const runtime=fs.readFileSync('game-tag-test/assets/js/validation-runtime.js','utf8');
const build=JSON.parse(fs.readFileSync('package-build.json','utf8'));
const buildId=build.game_build;
const cacheId=buildId.replace(/^GA-B/,'').replace('.','');
assert(html.includes('id="tagTestRunHealJson"'),'回復JSON検証ボタンがありません');
assert(runtime.includes("test:{id:'TAG-HEAL-DEVICE-001'"),'回復実機JSONテストIDがありません');
for(const id of ['HEAL-SINGLE','HEAL-ALL','HEAL-DEAD-REJECT','HEAL-ENEMY-REJECT','HEAL-INVALID-DATA-REJECT'])assert(runtime.includes(`'${id}'`),`${id} がありません`);
assert(runtime.includes("schema_version:'1.3.0'"),'過去形式に合わせたschema_versionがありません');
assert(runtime.includes("summary:{case_count:"),'AI判定用summaryがありません');
assert(runtime.includes('function ensureHealValidationFixtures()'),'回復検証fixture初期化がありません');
assert(runtime.includes("resetBattle();ensureHealValidationFixtures();"),'各ケース開始時にfixtureを初期化していません');
assert(runtime.includes("SKL-TEST-HEAL-100"),'単体回復fixtureがありません');
assert(runtime.includes("SKL-TEST-HEAL-ALL-60"),'全体回復fixtureがありません');
assert(runtime.includes('a.download=`tag-heal-device-validation-'),'回復JSONファイル名がありません');
assert(html.includes(`validation-runtime.js?v=${cacheId}`),'タグ検証ランタイムのキャッシュバスターが現行ビルドではありません');
assert(html.includes(`data.gameVersion='${buildId}'`),'タグ検証の保存ビルドが現行ビルドではありません');
const tagSw=fs.readFileSync('game-tag-test/sw.js','utf8');
assert(tagSw.includes(`ga-tag-test-b${cacheId}`),'タグ検証Service Workerキャッシュが現行ビルドではありません');
assert(tagSw.includes(`validation-runtime.js?v=${cacheId}`),'Service Workerが現行検証ランタイムを参照していません');
console.log('HEAL_DEVICE_JSON_CURRENT_BUILD_OK');
