const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('game-tag-test/index.html','utf8');
const runtime=fs.readFileSync('game-tag-test/assets/js/validation-runtime.js','utf8');
assert(html.includes('id="tagTestRunHealJson"'),'回復JSON検証ボタンがありません');
assert(runtime.includes("test:{id:'TAG-HEAL-DEVICE-001'"),'回復実機JSONテストIDがありません');
for(const id of ['HEAL-SINGLE','HEAL-ALL','HEAL-DEAD-REJECT','HEAL-ENEMY-REJECT','HEAL-INVALID-DATA-REJECT'])assert(runtime.includes(`'${id}'`),`${id} がありません`);
assert(runtime.includes("schema_version:'1.3.0'"),'過去形式に合わせたschema_versionがありません');
assert(runtime.includes("summary:{case_count:"),'AI判定用summaryがありません');
assert(runtime.includes("a.download=`tag-heal-device-validation-GA-B482-"),'回復JSONファイル名がありません');
console.log('HEAL_DEVICE_JSON_GA_B482_OK');
