const fs=require('fs'),assert=require('assert'),vm=require('vm');
const build=JSON.parse(fs.readFileSync('package-build.json','utf8'));
const runtimeConfig=fs.readFileSync('assets/shared/config/runtime-config.js','utf8');
const runtimeGameBuild=runtimeConfig.match(/gameBuild:\s*"([^"]+)"/)?.[1]||'';
const runtimeStudioBuild=runtimeConfig.match(/studioBuild:\s*"([^"]+)"/)?.[1]||'';
assert.strictEqual(build.game_build,runtimeGameBuild,'package-build game_build must match shared runtime-config');
assert.strictEqual(build.studio_build,runtimeStudioBuild,'package-build studio_build must match shared runtime-config');
const registry=JSON.parse(fs.readFileSync('assets/shared/config/skill-registry.json','utf8'));
const budgetRules=JSON.parse(fs.readFileSync('assets/shared/config/skill-budget-rules.json','utf8'));
const aiRules=JSON.parse(fs.readFileSync('assets/shared/config/skill-ai-generation-rules.json','utf8'));
const ctx={console};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of ['assets/shared/js/skill-budget-engine.js','assets/shared/js/formal-contribution-resolver.js','assets/shared/js/skill-compiler.js','assets/shared/js/formal-passive-compiler.js','assets/shared/js/skill-ai-batch-engine.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
(async()=>{
 const out=await ctx.GKSSkillAiBatchEngine.generateBatch({schema:'GKS_SKILL_AI_BATCH_REQUEST',version:'1.0.0',mode:'ACTIVE',requests:[
  {skillLevel:4,intent:'STR40物理',statThresholds:{STR:40},abilityKind:'PHYSICAL_DAMAGE',target:'ENEMY',range:'SINGLE',resource:{mpCost:999,cooldown:999,activationPriority:999,castTime:999},searchMetadata:{}},
  {skillLevel:8,intent:'AGI80三段',statThresholds:{AGI:80},abilityKind:'PHYSICAL_DAMAGE',target:'ENEMY',range:'SINGLE',resource:{mpCost:0,cooldown:0,activationPriority:0,castTime:0},searchMetadata:{}},
  {skillLevel:4,intent:'旧入力Reject',effects:[{type:'DAMAGE',damageType:'PHYSICAL'}],target:'ENEMY',range:'SINGLE',desiredStrength:'MEDIUM',resource:{mpCost:0,cooldown:0,activationPriority:0,castTime:0},searchMetadata:{}},
  {skillLevel:4,intent:'未Binding Heal',statThresholds:{MND:40},abilityKind:'HEAL',target:'ALLY',range:'SINGLE',resource:{mpCost:0,cooldown:0,activationPriority:0,castTime:0},searchMetadata:{}}
 ]},{registry,budgetRules,rules:aiRules,budgetEngine:ctx.GKSSkillBudgetEngine,compile:skill=>Promise.resolve(ctx.GKSSkillCompiler.compileSkill(skill,registry)),idPrefix:'G05-UI'});
 assert.deepStrictEqual(JSON.parse(JSON.stringify(out.summary)),{total:4,accepted:3,rejected:1,allAccepted:false});
 assert.strictEqual(out.entries[0].status,'ACCEPT');assert.deepStrictEqual(JSON.parse(JSON.stringify(out.entries[0].skill.abilityConditions)),[{stat:'STR',min:40}]);assert.strictEqual(out.entries[0].skill.effects[0].power,140);assert.strictEqual(out.entries[0].validation.budget,true);assert.strictEqual(out.entries[0].validation.compiler,true);
 assert.deepStrictEqual(JSON.parse(JSON.stringify(out.entries[0].skill.resource)),{mpCost:32,cooldown:0,activationPriority:0,castTime:0});assert.strictEqual(out.entries[0].generation.resourceSeedTrace.baseMpPerSkillLevel,8);
 assert.strictEqual(out.entries[1].status,'ACCEPT');assert.strictEqual(out.entries[1].skill.effects.length,3);assert.ok(out.entries[1].skill.effects.every(x=>x.power===60));
 assert.strictEqual(out.entries[2].status,'REJECT');assert.ok(out.entries[2].validation.issues.some(x=>x.code==='AI_STAT_THRESHOLDS_REQUIRED'));assert.ok(out.entries[2].validation.issues.some(x=>x.code==='AI_LEGACY_ACTIVE_EFFECTS_UNSUPPORTED'));
 assert.strictEqual(out.entries[3].status,'ACCEPT');assert.deepStrictEqual(JSON.parse(JSON.stringify(out.entries[3].skill.effects[0])),{type:'HEAL',power:40});

 const variableRules=JSON.parse(JSON.stringify(aiRules));variableRules.current_active.resource_policy.base_mp.per_skill_level=11;variableRules.current_active.resource_policy.ranges.FRONT={mp_multiplier:1.5,cooldown_tick:9,cast_time_tick:6};variableRules.current_active.resource_policy.ranges.RANDOM={mp_multiplier:2.25,cooldown_tick:5,cast_time_tick:3,target_count:4};
 const variable=ctx.GKSSkillAiBatchEngine.generateSkill({skillLevel:4,intent:'可変Resource',statThresholds:{STR:40},abilityKind:'PHYSICAL_DAMAGE',target:'ENEMY',range:'FRONT',resource:{mpCost:1,cooldown:1,activationPriority:88,castTime:1}},0,{registry,budgetRules,rules:variableRules,idPrefix:'G05-VAR',mode:'ACTIVE'});assert.deepStrictEqual(JSON.parse(JSON.stringify(variable.skill.resource)),{mpCost:66,cooldown:9,activationPriority:0,castTime:6});
 const random=ctx.GKSSkillAiBatchEngine.generateSkill({skillLevel:4,intent:'可変Random',statThresholds:{STR:40},abilityKind:'PHYSICAL_DAMAGE',target:'ENEMY',range:'RANDOM',randomCount:99},0,{registry,budgetRules,rules:variableRules,idPrefix:'G05-VAR',mode:'ACTIVE'});assert.strictEqual(random.skill.target.randomCount,4);assert.deepStrictEqual(JSON.parse(JSON.stringify(random.skill.resource)),{mpCost:99,cooldown:5,activationPriority:0,castTime:3});
 const badRules=JSON.parse(JSON.stringify(aiRules));delete badRules.current_active.resource_policy.ranges.ALL;assert.throws(()=>ctx.GKSSkillAiBatchEngine.generateSkill({skillLevel:4,intent:'設定欠落',statThresholds:{STR:40},abilityKind:'PHYSICAL_DAMAGE',target:'ENEMY',range:'ALL'},0,{registry,budgetRules,rules:badRules,idPrefix:'G05-VAR',mode:'ACTIVE'}),e=>e?.code==='ACTIVE_RANGE_RESOURCE_CONFIG_REQUIRED');
 assert.throws(()=>ctx.GKSSkillAiBatchEngine.generateSkill({skillLevel:4,intent:'PIERCE deferred',statThresholds:{STR:40},abilityKind:'PHYSICAL_DAMAGE',target:'ENEMY',range:'PIERCE'},0,{registry,budgetRules,rules:aiRules,idPrefix:'G05-VAR',mode:'ACTIVE'}),e=>e?.code==='ACTIVE_RANGE_RESOURCE_CONFIG_REQUIRED');
 const bound=await ctx.GKSSkillAiBatchEngine.generateBatch({schema:'GKS_SKILL_AI_BATCH_REQUEST',version:'1.0.0',mode:'ACTIVE',requests:[
  {skillLevel:4,intent:'攻撃強化STR40',statThresholds:{STR:40},abilityKind:'BUFF_ATTACK',activeBinding:{duration:25},target:'ALLY',range:'SINGLE'},
  {skillLevel:4,intent:'DOT DEX40',statThresholds:{DEX:40},abilityKind:'DOT',activeBinding:{effectId:'BURN',durationBudget:20},target:'ENEMY',range:'SINGLE'},
  {skillLevel:5,intent:'全状態解除',statThresholds:{MND:50},abilityKind:'CLEANSE_ALL',target:'ALLY',range:'SINGLE'},
  {skillLevel:3,intent:'Cover VIT30',statThresholds:{VIT:30},abilityKind:'COVER',activeBinding:{lifetime:'USES',uses:2,priority:7,removable:true},target:'ALLY',range:'SINGLE'},
  {skillLevel:4,intent:'Buff duration欠落',statThresholds:{STR:40},abilityKind:'BUFF_ATTACK',target:'ALLY',range:'SINGLE'},
  {skillLevel:4,intent:'Heal未接続',statThresholds:{MND:40},abilityKind:'HEAL',target:'ALLY',range:'SINGLE'}
 ]},{registry,budgetRules,rules:aiRules,budgetEngine:ctx.GKSSkillBudgetEngine,compile:skill=>Promise.resolve(ctx.GKSSkillCompiler.compileSkill(skill,registry)),idPrefix:'G05-BIND'});
 assert.deepStrictEqual(JSON.parse(JSON.stringify(bound.summary)),{total:6,accepted:5,rejected:1,allAccepted:false});
 assert.deepStrictEqual(JSON.parse(JSON.stringify(bound.entries[0].skill.effects[0])),{type:'APPLY',effectId:'ATK_UP',power:12,duration:25});assert.strictEqual(bound.entries[0].validation.compiler,true);
 assert.deepStrictEqual(JSON.parse(JSON.stringify(bound.entries[1].skill.effects[0])),{type:'APPLY',effectId:'BURN',power:5,duration:4,interval:1,stackGain:1});assert.strictEqual(bound.entries[1].generation.abilityBudgetTrace[0].completedTotal,20);assert.strictEqual(bound.entries[1].generation.abilityBudgetTrace[0].durationBudget,20);assert.strictEqual(bound.entries[1].generation.abilityBudgetTrace[0].durationBudgetPerTick,5);assert.strictEqual(bound.entries[1].generation.abilityBudgetTrace[0].intervalTicks,1);
 assert.deepStrictEqual(JSON.parse(JSON.stringify(bound.entries[2].skill.effects[0])),{type:'REMOVE',category:'STATUS',all:true});
 assert.deepStrictEqual(JSON.parse(JSON.stringify(bound.entries[3].skill.effects[0])),{type:'TARGET_CONTROL',mode:'COVER',trigger:'DIRECT_ATTACK',priority:7,removable:true,lifetime:'USES',uses:2});
 assert.ok(bound.entries[4].validation.issues.some(x=>x.code==='ACTIVE_BINDING_DURATION_REQUIRED'));assert.strictEqual(bound.entries[5].status,'ACCEPT');assert.deepStrictEqual(JSON.parse(JSON.stringify(bound.entries[5].skill.effects[0])),{type:'HEAL',power:40});
 const variableBindingRules=JSON.parse(JSON.stringify(aiRules));variableBindingRules.current_active.binding_policy.buff_debuff.power_per_budget=0.5;const variableBuff=ctx.GKSSkillAiBatchEngine.generateSkill({skillLevel:4,intent:'可変Buff係数',statThresholds:{STR:40},abilityKind:'BUFF_ATTACK',activeBinding:{duration:11},target:'ALLY',range:'SINGLE'},0,{registry,budgetRules,rules:variableBindingRules,idPrefix:'G05-BIND-VAR',mode:'ACTIVE'});assert.strictEqual(variableBuff.skill.effects[0].power,20);assert.strictEqual(variableBuff.skill.effects[0].duration,11);
 const variableDotRules=JSON.parse(JSON.stringify(aiRules));variableDotRules.current_active.binding_policy.dot.interval_ticks=2;const variableDot=ctx.GKSSkillAiBatchEngine.generateSkill({skillLevel:4,intent:'可変DOT interval',statThresholds:{DEX:40},abilityKind:'DOT',activeBinding:{effectId:'BURN',durationBudget:20},target:'ENEMY',range:'SINGLE'},0,{registry,budgetRules,rules:variableDotRules,idPrefix:'G05-BIND-VAR',mode:'ACTIVE'});assert.strictEqual(variableDot.skill.effects[0].interval,2);assert.strictEqual(variableDot.generation.abilityBudgetTrace[0].intervalTicks,2);
 const missingBindingRules=JSON.parse(JSON.stringify(aiRules));delete missingBindingRules.current_active.binding_policy.buff_debuff.power_per_budget;assert.throws(()=>ctx.GKSSkillAiBatchEngine.generateSkill({skillLevel:4,intent:'Binding config欠落',statThresholds:{STR:40},abilityKind:'BUFF_ATTACK',activeBinding:{duration:11},target:'ALLY',range:'SINGLE'},0,{registry,budgetRules,rules:missingBindingRules,idPrefix:'G05-BIND-VAR',mode:'ACTIVE'}),e=>e?.code==='ACTIVE_BINDING_CONFIG_REQUIRED');
 assert.strictEqual(out.mode,'ACTIVE');assert.strictEqual(out.aiGenerationRuleVersion,'G05-AI-GENERATION-V7-SKL-ACTIVE-BINDING-COMPLETE');assert.strictEqual(out.budgetRuleVersion,'SKL-THRESHOLD-BUDGET-V1');
 assert.throws(()=>ctx.GKSSkillAiBatchEngine.assertEnvelopeMode({schema:'GKS_SKILL_AI_BATCH_REQUEST',version:'1.0.0',requests:[]}),e=>e?.code==='AI_MODE_REQUIRED');
 const passive=await ctx.GKSSkillAiBatchEngine.generateBatch({schema:'GKS_SKILL_AI_BATCH_REQUEST',version:'1.0.0',mode:'PASSIVE',requests:[
  {intent:'HP自動回復',passiveSeriesId:'PASS-SER-14',stage:1,category:'Periodic',requirement:{VIT:20},effect:{kind:'PERIODIC_HP_REGEN',period_tick:20,max_hp_percent:1}},
  {intent:'最大HP上昇',passiveSeriesId:'PASS-SER-01',stage:1,category:'Modifier',requirement:{VIT:20},modifierChannel:'MAX_HP',effect:{channel:'MAX_HP',modifier_percent:5}},
  {intent:'属性耐性FIRE',passiveSeriesId:'PASS-SER-03',stage:1,category:'Modifier',requirement:{MND:20},modifierChannel:'ELEMENT_RESISTANCE:FIRE',effect:{channel:'ELEMENT_RESISTANCE:FIRE',modifier_percent:5}},
  {intent:'属性耐性未Binding',passiveSeriesId:'PASS-SER-03',stage:1,category:'Modifier',requirement:{MND:20},modifierChannel:'ELEMENT_RESISTANCE:<ELEMENT>',effect:{channel:'ELEMENT_RESISTANCE:<ELEMENT>',modifier_percent:5}},
  {intent:'瀕死時強化可変',passiveSeriesId:'PASS-SER-17',stage:1,category:'Composite Special',requirement:{VIT:60},effect:{kind:'LOW_HP_BURST',hp_threshold_percent:7,duration_tick:33,modifier_bonus_percent:45,action_gauge_gain_bonus_percent:45,cooldown_tick:777}},
  {intent:'致死耐え可変',passiveSeriesId:'PASS-SER-16',stage:1,category:'Special Trigger',requirement:{VIT:80},effect:{kind:'LETHAL_SURVIVE',survive_hp:3,cooldown_tick:456}},
  {intent:'混在Reject',passiveSeriesId:'PASS-SER-X',stage:1,category:'Periodic',requirement:{VIT:20},skillLevel:2,effect:{kind:'PERIODIC_HP_REGEN',period_tick:20,max_hp_percent:1}}
 ]},{registry,rules:aiRules,compilePassive:ctx.GKSFormalPassiveCompiler.compilePassive,passiveSkills:[],validateFinal:true,passiveIdPrefix:'G05-PAS'});
 assert.deepStrictEqual(JSON.parse(JSON.stringify(passive.summary)),{total:7,accepted:5,rejected:2,allAccepted:false});assert.strictEqual(passive.mode,'PASSIVE');
 assert.strictEqual(passive.entries[0].status,'ACCEPT');assert.strictEqual(passive.entries[0].passive.passiveSeriesId,'PASS-SER-14');assert.deepStrictEqual(JSON.parse(JSON.stringify(passive.entries[0].passive.params.ability_conditions)),[{stat:'VIT',min:20}]);assert.deepStrictEqual(JSON.parse(JSON.stringify(passive.entries[0].passive.runtimeContracts.periodicContract)),{resource:'HP',intervalTicks:20,initialDelayTicks:20,recoveryRate:0.01});
 assert.strictEqual(passive.entries[1].status,'ACCEPT');assert.strictEqual(passive.entries[1].modifierCandidate.definition.target,'MAX_HP');assert.strictEqual(passive.entries[1].modifierCandidate.definition.operation,'RELATIVE_PERCENT');assert.strictEqual(passive.entries[1].modifierCandidate.balance.value,0.05);assert.deepStrictEqual(JSON.parse(JSON.stringify(passive.entries[1].passive.params.mod_ids)),[passive.entries[1].modifierCandidate.definition.id]);
 const checkedGeneratedMod=ctx.GKSFormalContribution.validateModCandidate(passive.entries[1].modifierCandidate);assert.strictEqual(checkedGeneratedMod.definition.target,'MAX_HP');assert.strictEqual(checkedGeneratedMod.balance.value,0.05);
 assert.strictEqual(passive.entries[2].status,'ACCEPT');assert.strictEqual(passive.entries[2].modifierCandidate.definition.target,'ELEMENT_RESISTANCE:FIRE');assert.strictEqual(passive.entries[2].modifierCandidate.definition.operation,'ADDITIVE_POINT');assert.strictEqual(passive.entries[2].modifierCandidate.balance.value,5);
 assert.ok(passive.entries[3].validation.issues.some(x=>x.code==='PASSIVE_PARAMETER_BINDING_REQUIRED'));
 assert.strictEqual(passive.entries[4].status,'ACCEPT');assert.deepStrictEqual(JSON.parse(JSON.stringify(passive.entries[4].passive.runtimeContracts.lowHpContract)),{hpThresholdRate:0.07,durationTicks:33,cooldownTicks:777,relativeBonus:0.45,contributionTargets:['PHYSICAL_DAMAGE','MAGIC_DAMAGE','ACCURACY','MAGIC_ACCURACY','EVASION','BLOCK_RATE','BLOCK_PERFORMANCE','CRITICAL_RATE','CRITICAL_DAMAGE','ACTION_GAUGE_GAIN']});
 assert.strictEqual(passive.entries[5].status,'ACCEPT');assert.strictEqual(passive.entries[5].passive.runtimeContracts.triggerContract.type,'ON_FATAL_DAMAGE');assert.strictEqual(passive.entries[5].passive.runtimeContracts.triggerContract.cooldownTicks,456);assert.strictEqual(passive.entries[5].passive.runtimeContracts.triggerContract.surviveHp,3);
 assert.ok(passive.entries[6].validation.issues.some(x=>x.code==='AI_MODE_FIELD_MIXED'));
 const explicit=await ctx.GKSSkillAiBatchEngine.generateBatch({schema:'GKS_SKILL_AI_BATCH_REQUEST',version:'1.0.0',mode:'PASSIVE',requests:[{intent:'既存MOD参照',passiveSeriesId:'PASS-SER-01',stage:1,category:'Modifier',requirement:{VIT:20},modifierChannel:'MAX_HP',modifierRefs:{modIds:['MOD-EXPLICIT'],effectIds:[],combatCapabilities:[]}}]},{registry,rules:aiRules,validateFinal:false});assert.strictEqual(explicit.entries[0].status,'ACCEPT');assert.deepStrictEqual(JSON.parse(JSON.stringify(explicit.entries[0].passive.params.mod_ids)),['MOD-EXPLICIT']);
 const passiveCompilerSrc=fs.readFileSync('assets/shared/js/formal-passive-compiler.js','utf8'),gameTagRuntimeSrc=fs.readFileSync('game/assets/js/tag-skill-runtime.js','utf8'),studioRuntimeSrc=fs.readFileSync('studio/index.html','utf8');assert.ok(passiveCompilerSrc.includes('triggerContract.surviveHp=surviveHp'));assert.ok(passiveCompilerSrc.includes('relativeBonus=params.lowHp.relativeBonus'));assert.ok(gameTagRuntimeSrc.includes("resolvedHp=surviveHp"));assert.ok(gameTagRuntimeSrc.includes("'MAGIC_RESISTANCE'"));assert.ok(studioRuntimeSrc.includes('const resolvedHp=surviveHp'));
 const sg=fs.readFileSync('studio/skill/skill-generator.js','utf8');
 for(const marker of ['data-ai-batch-filter="ALL"','data-ai-batch-filter="ACCEPT"','data-ai-batch-filter="REJECT"','data-ai-batch-status','Registry','Budget','Compiler','Studio生成数値 / Threshold trace','x.code||\'REJECT\'','x.path'])assert.ok(sg.includes(marker),`G05 stage2 UI marker missing: ${marker}`);
 const html=fs.readFileSync('studio/index.html','utf8');assert.ok(html.includes('skill-compiler.js?v=486180'));assert.ok(html.includes('skill-budget-engine.js?v=3'));assert.ok(html.includes('skill-ai-batch-engine.js?v=7'));assert.ok(html.includes('skill-generator.js?v=37'));assert.ok(!html.includes('generic-skill-compiler.js'));
 console.log('SKILL_GENERATOR_G05_BATCH_UI_GKS_B533_PASS');
})().catch(e=>{console.error(e);process.exit(1)});
