const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const registry=JSON.parse(fs.readFileSync('assets/shared/config/skill-registry.json','utf8'));
const compiler=require('../assets/shared/js/skill-compiler.js');
const ctx={console,battle:{tick:0,units:[],log:[]}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('game/assets/js/tag-skill-runtime.js','utf8'),ctx);
const skill={schemaVersion:1,id:'SKL-9460',name:'Formal DOT compatibility boundary',trigger:{type:'ON_USE',scope:'SELF'},conditions:[],target:{side:'ENEMY',range:'SINGLE'},effects:[{type:'APPLY',effectId:'BURN',power:10,duration:300,interval:100,stackGain:1}],resource:{mpCost:0,cooldown:0}};
const out=compiler.compileSkill(skill,registry);assert.strictEqual(out.ok,true,JSON.stringify(out.errors));assert.ok(out.compiledSkill.runtimeContracts,'Formal compiler did not emit runtimeContracts');const runtime=ctx.compileSkillForRuntime(out.compiledSkill);assert.strictEqual(runtime.ok,true,JSON.stringify(runtime.errors));assert.ok(runtime.definition.logicOrder.includes('DOT'));
assert.strictEqual(typeof ctx.compileTaggedSkill,'undefined','Legacy compileTaggedSkill must not return');assert.strictEqual(ctx.compileSkillForRuntime({id:'LEGACY-DOT',name:'Legacy DOT',tags:['DOT']}).ok,false,'tag-only Legacy DOT must be rejected');
console.log('FORMAL_DOT_COMPAT_BOUNDARY_GA_B459_PASS');
