const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'studio/skill/skill-generator.js'),'utf8');
const index=fs.readFileSync(path.join(root,'studio/index.html'),'utf8');
const config=fs.readFileSync(path.join(root,'assets/shared/config/runtime-config.js'),'utf8');
function need(cond,msg){if(!cond)throw new Error(msg);}
const sm=config.match(/studioBuild:\s*"([^"]+)"/),gm=config.match(/gameBuild:\s*"([^"]+)"/);
need(sm&&gm,'runtime build config missing');
need(/const VERSION='1\.[1-9][0-9]*\.0'/.test(js),'skill generator version regression');
need(js.includes('③ 選択した効果の設定'),'dynamic effect settings section missing');
need(js.includes('runtimeFields={ATTACK:'),'runtime field map missing');
need(js.includes('renderDynamic()'),'dynamic renderer missing');
need(js.includes('skg-fixed-op'),'fixed equals UI missing');
need(js.includes("textContent='固定値として実行タグへ出力'"),'fixed value explanation missing');
need(js.includes('④ 検索・分類'),'search/classification separation missing');
need(js.includes('⑤ AI・JSON一括'),'AI JSON fold section missing');
need(js.includes("q('skgManualGenerate').disabled=missing.length>0"),'required field generation lock missing');
need(js.includes("if(q('skgRange')?.value==='ランダム')add('RANDOM_COUNT')"),'random count dynamic requirement missing');
need(js.includes('.skg-runtime-grid input[type=checkbox]'),'mobile checkbox override missing');
need(js.includes('width:22px!important'),'mobile checkbox fixed width lost');
need(index.includes(sm[1]),'Studio build display out of sync');
need(index.includes(gm[1]),'Game build display out of sync');
need(/\.\/skill\/skill-generator\.js\?v=\d+/.test(index),'skill generator cache key missing');
console.log('SKILL_GENERATOR_COMPACT_UI_REGRESSION_PASS');
