'use strict';
const fs=require('fs'), path=require('path'), assert=require('assert');
const html=fs.readFileSync(path.join(__dirname,'..','studio','index.html'),'utf8');
assert(html.includes("DELETE_PLANNED_PROTECTED"), 'protected delete preview status missing');
assert(html.includes("DELETE_MANIFEST削除予定（承認前プレビュー）"), 'pre-approval preview missing');
assert(html.includes("normalButton.disabled=false"), 'normal approval button must accept click for feedback');
assert(html.includes("protectedButton.disabled=false"), 'protected approval button must accept click for feedback');
assert(html.includes("更新ZIPが未選択です。先にZIPを読み込んでください。"), 'missing no-package feedback');
assert(html.includes("保護領域削除許可の前に、通常の削除許可をONにしてください。"), 'missing approval-order feedback');
assert(html.includes("差分を再解析"), 'explicit diff reanalysis control missing');
const toggle=html.match(/async function toggleDeployDeleteApproval\(kind\)\{[\s\S]*?\n\}/);
assert(toggle && !toggle[0].includes("prepareStudioDeployDiff"), 'approval toggle must not fetch GitHub diff');
console.log('PASS test_studio_delete_preview_and_approval_feedback_gks_b557');
