const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('game-tag-test/index.html','utf8');
const runtime=fs.readFileSync('game-tag-test/assets/js/validation-runtime.js','utf8');
const rootSw=fs.readFileSync('sw.js','utf8');
assert(html.includes('id="tagTestRunHealJson"'),'回復JSON検証ボタンがありません');
assert(runtime.includes("build:'GA-B484.1'"),'JSON buildがGA-B484.1ではありません');
assert(runtime.includes('tag-heal-device-validation-GA-B484.1-'),'JSONファイル名がGA-B484.1ではありません');
assert(runtime.includes('ensureHealValidationFixtures'),'回復検証fixtureがありません');
assert(rootSw.includes('ga-root-b4841'),'ルートService Workerキャッシュが更新されていません');
console.log('HEAL_DEVICE_JSON_GA_B483_2_OK');
