const assert=require('assert');
const validator=require('../data-exchange-integrity-validator.js');
global.GKSDataExchangeIntegrityValidator=validator;
const dx=require('../data-exchange-core.js');

(async()=>{
  assert.equal(dx.FORMAT,'GKS_DATA_EXCHANGE');
  const a={id:'MON-1',tags:['B','A'],updated_at:'x',params:{skill_ids:['S2','S1']}};
  const b={id:'MON-1',tags:['A','B'],updated_at:'y',params:{skill_ids:['S1','S2']}};
  assert.equal(dx.stableStringify(dx.canonicalizeRecord('monsters',a)),dx.stableStringify(dx.canonicalizeRecord('monsters',b)),'unordered/volatile normalization');
  const root={schema_version:'4.0.0-draft',project:{id:'P1',updated_at:'R1'},tags:[{id:'T1',name:'Tag'}],masters:{monsters:[{id:'M1',name:'Monster',tags:['T1'],params:{skill_ids:['S1']}}],skills:[{id:'S1',name:'Skill',tags:['T1'],params:{required_tags:['T1']}}],jobs:[],equipment:[],mods:[],ai_conditions:[],ai_targets:[],ai_actions:[]}};
  const env=await dx.buildEnvelope({rootData:root,dataset:'monsters',ids:['M1'],dependencyMode:'recursive',studioVersion:'TEST'});
  assert.equal(env.datasets.monsters.length,1);
  assert.equal(env.datasets.tags.length,1);
  assert.equal(env.datasets.skills.length,1);
  assert.deepEqual(env.permissions.writable,['monsters']);
  assert(env.permissions.read_only.includes('tags'));
  assert.equal(env.metadata.package_hash.length,64);
  assert.equal(env.metadata.record_hashes.monsters.M1.length,64);
  assert(dx.validateEnvelopeShape(env).ok);
  const allRoot={schema_version:'4.0.0-draft',project:{id:'P2',updated_at:'R2'},tags:[{id:'T1'}],masters:{monsters:[],skills:[],jobs:[],equipment:[],mods:[],stats:[{id:'STAT-1',name:'Stat',tags:['T1']}],status_effects:[{id:'SE-1',name:'Status',tags:['T1']}],tablets:[{id:'TAB-1',name:'Tablet',tags:['T1']}],ai_conditions:[],ai_targets:[],ai_actions:[]}};
  for(const ds of ['stats','status_effects','tablets']){const out=await dx.buildEnvelope({rootData:allRoot,dataset:ds,ids:[dx.records(allRoot,ds)[0].id],dependencyMode:'direct',studioVersion:'TEST'});assert.equal(out.datasets[ds].length,1);assert.deepEqual(out.permissions.writable,[ds]);assert.equal(out.datasets.tags.length,1);}
  const unchanged=await dx.dryRunImport({rootData:root,envelope:env});
  assert.equal(unchanged.ok,true);assert.equal(unchanged.summary.unchanged,1);assert.equal(unchanged.can_apply,false);
  const changed=JSON.parse(JSON.stringify(env));changed.datasets.monsters[0].name='Changed';changed.metadata.package_hash='';
  assert.equal((await dx.dryRunImport({rootData:root,envelope:changed})).summary.conflict,1);
  const added=JSON.parse(JSON.stringify(env));added.datasets.monsters[0].id='M2';added.datasets.monsters[0].params.skill_ids=[];added.metadata.base_hash='';added.metadata.package_hash='';
  const addedResult=await dx.dryRunImport({rootData:root,envelope:added});
  assert.equal(addedResult.summary.add,1);
  assert.equal(addedResult.impact_preview.summary.direct,1);
  assert(addedResult.impact_preview.direct.some(x=>x.dataset==='monsters'&&x.id==='M2'&&x.status==='add'));
  const broken=JSON.parse(JSON.stringify(added));broken.datasets.monsters[0].params.skill_ids=['MISSING'];
  const brokenResult=await dx.dryRunImport({rootData:root,envelope:broken});assert.equal(brokenResult.summary.broken_reference,1);assert.equal(brokenResult.ok,true);assert.equal(brokenResult.integrity.apply_blocking,true);
  const roEnv=JSON.parse(JSON.stringify(env));roEnv.datasets.tags[0].name='ChangedTag';roEnv.metadata.package_hash='';
  const roResult=await dx.dryRunImport({rootData:root,envelope:roEnv});assert.equal(roResult.summary.readonly_modified,1);assert.equal(roResult.ok,true);assert.equal(roResult.integrity.apply_blocking,true);
  const addDry=await dx.dryRunImport({rootData:root,envelope:added});
  assert.equal(addDry.can_apply,true);
  const addPlan=await dx.createApplyPlan({rootData:root,envelope:added,dryRun:addDry});
  assert.equal(addPlan.can_apply,true);assert.equal(addPlan.add_count,1);assert.deepEqual(addPlan.ids,['M2']);
  const applied=await dx.applySafeMerge({rootData:root,envelope:added,plan:addPlan,dryRun:addDry});
  assert.equal(dx.records(root,'monsters').length,1,'source root must not be mutated');
  assert.equal(dx.records(applied.nextRootData,'monsters').length,2);
  assert.equal(applied.verify.summary.unchanged,1);
  assert.equal(applied.verify.summary.add,0);
  const conflictPlan=await dx.createApplyPlan({rootData:root,envelope:changed});
  assert.equal(conflictPlan.can_apply,false);assert(conflictPlan.reasons.some(x=>x.includes('競合')));
  const brokenPlan=await dx.createApplyPlan({rootData:root,envelope:broken});
  assert.equal(brokenPlan.can_apply,false);assert(brokenPlan.reasons.some(x=>x.includes('参照切れ')));
  const noChangePlan=await dx.createApplyPlan({rootData:root,envelope:env});
  assert.equal(noChangePlan.can_apply,false);assert(noChangePlan.reasons.some(x=>x.includes('追加対象')));
  const normalConflict=JSON.parse(JSON.stringify(env));normalConflict.datasets.monsters[0].name='GPTChanged';normalConflict.metadata.package_hash='';
  const normalConflictResult=await dx.dryRunImport({rootData:root,envelope:normalConflict});
  assert.equal(normalConflictResult.summary.conflict,1);
  assert.equal(normalConflictResult.summary.stale_source,0,'normal GPT edit must not be stale when current source record is unchanged');
  assert.equal(normalConflictResult.impact_preview.summary.direct,1);
  const conflictImpact=normalConflictResult.impact_preview.direct.find(x=>x.dataset==='monsters'&&x.id==='M1');
  assert(conflictImpact&&conflictImpact.diffs.some(d=>d.path==='name'),'conflict preview must expose field-level diff');

  const staleRoot=JSON.parse(JSON.stringify(root));staleRoot.project.updated_at='R2';staleRoot.masters.monsters[0].name='ServerChanged';
  const staleImport=JSON.parse(JSON.stringify(env));staleImport.datasets.monsters[0].name='GPTChanged';staleImport.metadata.package_hash='';
  const staleResult=await dx.dryRunImport({rootData:staleRoot,envelope:staleImport});
  assert.equal(staleResult.summary.stale_source,1);
  assert.equal(staleResult.summary.conflict,0,'stale_source must take precedence over normal conflict for a changed source record');
  assert(staleResult.items.some(x=>x.status==='stale_source'&&x.id==='M1'));
  assert(!staleResult.items.some(x=>x.status==='conflict'&&x.id==='M1'));
  assert.equal(staleResult.can_apply,false);

  const revisionOnlyRoot=JSON.parse(JSON.stringify(root));revisionOnlyRoot.project.updated_at='R2';
  const revisionOnlyResult=await dx.dryRunImport({rootData:revisionOnlyRoot,envelope:env});
  assert.equal(revisionOnlyResult.summary.stale_source,0,'unrelated project revision change must not stale an unchanged selected record');
  assert.equal(revisionOnlyResult.source_revision.changed,true);

  const legacyStale=JSON.parse(JSON.stringify(env));delete legacyStale.metadata.record_hashes;legacyStale.metadata.package_hash='';
  const legacyStaleResult=await dx.dryRunImport({rootData:staleRoot,envelope:legacyStale});
  assert.equal(legacyStaleResult.summary.stale_source,1,'legacy base_hash fallback must remain supported');

  const preview=dx.buildImpactPreview(root,env,unchanged);
  assert.equal(preview.summary.direct,0);
  assert(preview.summary.existing_references>=1,'read_only dependencies already present must be shown as existing references');
  assert(preview.unaffected.includes('jobs'),'unrelated datasets must be listed as unaffected');

  const incompatible=JSON.parse(JSON.stringify(env));incompatible.project_id='OTHER';incompatible.metadata.package_hash='';
  assert.equal((await dx.dryRunImport({rootData:root,envelope:incompatible})).summary.incompatible,1);
  const schemaBad=JSON.parse(JSON.stringify(env));schemaBad.metadata.schema_version='OLD';schemaBad.metadata.package_hash='';
  assert.equal((await dx.dryRunImport({rootData:root,envelope:schemaBad})).summary.incompatible,1);
  const duplicate=JSON.parse(JSON.stringify(env));duplicate.datasets.monsters.push(JSON.parse(JSON.stringify(duplicate.datasets.monsters[0])));duplicate.metadata.record_count.monsters=2;duplicate.metadata.package_hash='';
  assert((await dx.dryRunImport({rootData:root,envelope:duplicate})).summary.invalid>=1);
  const countBad=JSON.parse(JSON.stringify(env));countBad.metadata.record_count.monsters=99;countBad.metadata.package_hash='';
  assert((await dx.dryRunImport({rootData:root,envelope:countBad})).summary.invalid>=1);
  const deleteBad=JSON.parse(JSON.stringify(env));deleteBad.operations={delete:['M1']};deleteBad.metadata.package_hash='';
  assert((await dx.dryRunImport({rootData:root,envelope:deleteBad})).summary.invalid>=1);
  console.log('Data Exchange core tests: PASS');
})().catch(e=>{console.error(e);process.exit(1)});
