const assert=require('assert');
const fs=require('fs');
const path=require('path');
const dx=require('../data-exchange-core.js');
const tx=require('../data-exchange-transaction.js');
const audit=require('../data-exchange-audit.js');
const clone=x=>JSON.parse(JSON.stringify(x));
class MemoryStorage{constructor(){this.map=new Map()}getItem(k){return this.map.has(k)?this.map.get(k):null}setItem(k,v){this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}}
function baseProject(){return {schema_version:'4.0.0-draft',project:{id:'PRJ-DE20',updated_at:'R1'},chapters:[{id:'CHP-0001',no:1,title:'Base Chapter',theme:'',summary:'Base',status:'draft',design:{goal:'',source_version:1},sections:[{id:'SEC-0001',no:1,title:'Base Section',summary:'',purpose:'',start_state:'',end_state:'',key_points:'',status:'draft',design:{goal:'',source_version:1},scenes:[{id:'SCN-0001',no:1,title:'Base Scene',summary:'',status:'draft',dialogues:[{id:'DLG-0001',no:1,status:'draft',speaker:'Hero',text:'Hello',stage_direction:''}]}]}],candidate_revisions:[],export_control:{ready:false,approved_revision_id:'',canonical_hash:'',marked_at:'',marked_by:''},created_at:'TAG-0000',updated_at:'TAG-0001'}],masters:{monsters:[],skills:[],stats:[],status_effects:[],tablets:[],jobs:[],mods:[],equipment:[],ai_conditions:[],ai_targets:[],ai_actions:[]},tags:[],tag_categories:[],history:[]}}
async function makeAdd(base,id){const env=await dx.buildEnvelope({rootData:base,dataset:'chapters',ids:['CHP-0001'],dependencyMode:'recursive',studioVersion:'TEST-DE20'});const out=clone(env),row=out.datasets.chapters[0];row.id=id;row.no=2;row.title='DE20 Story';row.summary='Story vertical';row.sections=[{id:'SEC-0002',no:1,title:'Section',summary:'',purpose:'',start_state:'',end_state:'',key_points:'',status:'draft',design:{goal:'',source_version:1},scenes:[{id:'SCN-0002',no:1,title:'Scene',summary:'',status:'draft',dialogues:[{id:'DLG-0002',no:1,status:'draft',speaker:'Narrator',text:'DE20',stage_direction:''}]}]}];row.candidate_revisions=[];row.export_control={ready:false,approved_revision_id:'',canonical_hash:'',marked_at:'',marked_by:''};out.metadata.base_hash='';out.metadata.record_hashes={chapters:{}};out.metadata.package_hash='';return out}
async function main(){
 const base=baseProject();
 const html=fs.readFileSync(path.resolve(__dirname,'../../index.html'),'utf8');
 assert(html.includes('data-exchange-core.js?v=18'),'DE-20 core cache key');
 assert(html.includes('data-exchange-ui.js?v=23r1'),'DE-20 UI cache key');
 assert(html.includes('GKSDataExchangeUI.openStoryPicker()'),'Story Data Exchange scenario entry');
 const ui=fs.readFileSync(path.resolve(__dirname,'../data-exchange-ui.js'),'utf8');
 assert(ui.includes("datasets:['chapters','story_sections','story_scenes','story_dialogues']"),'Story-only picker datasets');
 assert(ui.includes("title:'シナリオ データ出力'"),'Story-only picker title');
 assert(fs.existsSync(path.resolve(__dirname,'../schemas/chapter-dataset.schema.json')),'chapter schema');
 const env=await dx.buildEnvelope({rootData:base,dataset:'chapters',ids:['CHP-0001'],dependencyMode:'recursive',studioVersion:'TEST-DE20'});
 assert.deepEqual(env.permissions.writable,['chapters']);assert.deepEqual(env.permissions.read_only,[]);assert.equal(env.datasets.chapters.length,1);assert.equal(env.datasets.chapters[0].sections[0].scenes[0].dialogues[0].text,'Hello');
 const add=await makeAdd(base,'CHP-0002');const dry=await dx.dryRunImport({rootData:base,envelope:add});assert.equal(dry.summary.add,1);assert.equal(dry.can_apply,true);
 const plan=await dx.createApplyPlan({rootData:base,envelope:add,dryRun:dry});assert.equal(plan.can_apply,true,plan.reasons.join(' / '));
 let live=clone(base),before=clone(base);const tr=await tx.execute({rootData:live,envelope:add,plan,dryRun:dry,backup:()=>true,commit:c=>{live=c;return true;},persist:()=>true,rollback:b=>{live=b;return true;}});assert.equal(tr.ok,true);assert.equal(live.chapters.find(x=>x.id==='CHP-0002').sections[0].scenes[0].dialogues[0].text,'DE20');
 const store=new MemoryStorage();const session=audit.buildSession({transaction:tr,plan,envelope:add,beforeData:before,afterHash:await tx.projectHash(live),beforeDatasetHash:await audit.datasetHash(before,'chapters'),afterDatasetHash:await audit.datasetHash(live,'chapters'),sourceFilename:'DE20_STORY.json'});assert(audit.append(store,'audit',session));const undo=await audit.undo({session,currentData:live,normalize:x=>x,validate:x=>audit.validateSnapshot(x,session),backup:()=>true,commit:c=>{live=c;return true;},persist:()=>true,readCurrent:()=>live,rollback:b=>{live=b;return true;}});assert.equal(live.chapters.some(x=>x.id==='CHP-0002'),false);assert(audit.markUndone(store,'audit',session.import_session_id,undo.undoAfterHash));
 const unknown=await makeAdd(base,'CHP-0003');unknown.datasets.chapters[0].future_story_payload={unsafe:true};unknown.metadata.package_hash='';const ud=await dx.dryRunImport({rootData:base,envelope:unknown});const up=await dx.createApplyPlan({rootData:base,envelope:unknown,dryRun:ud});assert.equal(up.can_apply,false);assert(up.reasons.some(x=>x.includes('未知フィールド')));
 const existing=await dx.buildEnvelope({rootData:base,dataset:'chapters',ids:['CHP-0001'],dependencyMode:'none',studioVersion:'TEST-DE20'});const changed=clone(existing);changed.datasets.chapters[0].summary='GPT changed';changed.metadata.package_hash='';const cd=await dx.dryRunImport({rootData:base,envelope:changed});assert.equal(cd.summary.conflict,1);assert.equal((await dx.createApplyPlan({rootData:base,envelope:changed,dryRun:cd})).can_apply,false);assert.equal((await dx.createApplyPlan({rootData:base,envelope:changed,dryRun:cd,conflictChoices:{'CHP-0001':'import'}})).can_apply,true);
 const stale=clone(base);stale.chapters[0].summary='Changed after export';const sd=await dx.dryRunImport({rootData:stale,envelope:existing});assert.equal(sd.summary.stale_source,1);assert.equal(sd.can_apply,false);
 const del=clone(add);del.operations={delete:{chapters:['CHP-0002']}};del.metadata.package_hash='';const dd=await dx.dryRunImport({rootData:base,envelope:del});assert.equal(dd.can_apply,false);assert(dd.summary.invalid+dd.summary.incompatible>=1);

 // Nested Story partial exchange: keep canonical nesting while editing one child level.
 const sectionRows=dx.records(base,'story_sections');assert.equal(sectionRows.length,1);assert.equal(sectionRows[0].chapter_id,'CHP-0001');assert.equal('scenes' in sectionRows[0],false);
 const sceneRows=dx.records(base,'story_scenes');assert.equal(sceneRows.length,1);assert.equal(sceneRows[0].section_id,'SEC-0001');assert.equal('dialogues' in sceneRows[0],false);
 const dialogueRows=dx.records(base,'story_dialogues');assert.equal(dialogueRows.length,1);assert.equal(dialogueRows[0].scene_id,'SCN-0001');assert.equal(dialogueRows[0].text,'Hello');
 const sectionExport=await dx.buildEnvelope({rootData:base,dataset:'story_sections',ids:['SEC-0001'],dependencyMode:'none',studioVersion:'TEST-NESTED'});assert.deepEqual(sectionExport.permissions.writable,['story_sections']);assert.equal(sectionExport.datasets.story_sections[0].chapter_id,'CHP-0001');assert.equal('scenes' in sectionExport.datasets.story_sections[0],false);

 const sectionAdd=clone(sectionExport);sectionAdd.datasets.story_sections[0]={...sectionAdd.datasets.story_sections[0],id:'SEC-0003',no:2,title:'New Section',summary:'partial add'};sectionAdd.metadata.base_hash='';sectionAdd.metadata.record_hashes={story_sections:{}};sectionAdd.metadata.package_hash='';
 const sectionDry=await dx.dryRunImport({rootData:base,envelope:sectionAdd});assert.equal(sectionDry.summary.add,1);assert.equal(sectionDry.can_apply,true);const sectionPlan=await dx.createApplyPlan({rootData:base,envelope:sectionAdd,dryRun:sectionDry});let sectionLive=clone(base);const sectionTx=await tx.execute({rootData:sectionLive,envelope:sectionAdd,plan:sectionPlan,dryRun:sectionDry,backup:()=>true,commit:c=>{sectionLive=c;return true;},persist:()=>true,rollback:b=>{sectionLive=b;return true;}});assert.equal(sectionTx.ok,true);assert.equal(sectionLive.chapters[0].sections.length,2);assert.equal(sectionLive.chapters[0].sections[0].scenes[0].dialogues[0].text,'Hello');assert.deepEqual(sectionLive.chapters[0].sections.find(x=>x.id==='SEC-0003').scenes,[]);
 const sectionStore=new MemoryStorage();const sectionSession=audit.buildSession({transaction:sectionTx,plan:sectionPlan,envelope:sectionAdd,beforeData:base,afterHash:await tx.projectHash(sectionLive),beforeDatasetHash:await audit.datasetHash(base,'story_sections'),afterDatasetHash:await audit.datasetHash(sectionLive,'story_sections'),sourceFilename:'SECTION.json'});assert(audit.append(sectionStore,'audit',sectionSession));await audit.undo({session:sectionSession,currentData:sectionLive,normalize:x=>x,validate:x=>audit.validateSnapshot(x,sectionSession),backup:()=>true,commit:c=>{sectionLive=c;return true;},persist:()=>true,readCurrent:()=>sectionLive,rollback:b=>{sectionLive=b;return true;}});assert.equal(sectionLive.chapters[0].sections.length,1);assert.equal(sectionLive.chapters[0].sections[0].scenes[0].dialogues[0].text,'Hello');

 const sceneExport=await dx.buildEnvelope({rootData:base,dataset:'story_scenes',ids:['SCN-0001'],dependencyMode:'none',studioVersion:'TEST-NESTED'});const sceneAdd=clone(sceneExport);sceneAdd.datasets.story_scenes[0]={...sceneAdd.datasets.story_scenes[0],id:'SCN-0003',no:2,title:'New Scene'};sceneAdd.metadata.base_hash='';sceneAdd.metadata.record_hashes={story_scenes:{}};sceneAdd.metadata.package_hash='';const sceneDry=await dx.dryRunImport({rootData:base,envelope:sceneAdd});assert.equal(sceneDry.summary.add,1);const scenePlan=await dx.createApplyPlan({rootData:base,envelope:sceneAdd,dryRun:sceneDry});const sceneApplied=await dx.applySafeMerge({rootData:base,envelope:sceneAdd,plan:scenePlan,dryRun:sceneDry});assert.equal(sceneApplied.nextRootData.chapters[0].sections[0].scenes.length,2);assert.equal(sceneApplied.nextRootData.chapters[0].sections[0].scenes[0].dialogues[0].text,'Hello');assert.deepEqual(sceneApplied.nextRootData.chapters[0].sections[0].scenes.find(x=>x.id==='SCN-0003').dialogues,[]);

 const dialogueExport=await dx.buildEnvelope({rootData:base,dataset:'story_dialogues',ids:['DLG-0001'],dependencyMode:'none',studioVersion:'TEST-NESTED'});const dialogueAdd=clone(dialogueExport);dialogueAdd.datasets.story_dialogues[0]={...dialogueAdd.datasets.story_dialogues[0],id:'DLG-0003',no:2,text:'Partial dialogue'};dialogueAdd.metadata.base_hash='';dialogueAdd.metadata.record_hashes={story_dialogues:{}};dialogueAdd.metadata.package_hash='';const dialogueDry=await dx.dryRunImport({rootData:base,envelope:dialogueAdd});assert.equal(dialogueDry.summary.add,1);const dialoguePlan=await dx.createApplyPlan({rootData:base,envelope:dialogueAdd,dryRun:dialogueDry});const dialogueApplied=await dx.applySafeMerge({rootData:base,envelope:dialogueAdd,plan:dialoguePlan,dryRun:dialogueDry});assert.equal(dialogueApplied.nextRootData.chapters[0].sections[0].scenes[0].dialogues.length,2);assert.equal(dialogueApplied.nextRootData.chapters[0].sections[0].scenes[0].dialogues.find(x=>x.id==='DLG-0003').text,'Partial dialogue');

 const sectionEdit=clone(sectionExport);sectionEdit.datasets.story_sections[0].title='Edited Section';sectionEdit.metadata.package_hash='';const sectionEditDry=await dx.dryRunImport({rootData:base,envelope:sectionEdit});assert.equal(sectionEditDry.summary.conflict,1);const sectionEditPlan=await dx.createApplyPlan({rootData:base,envelope:sectionEdit,dryRun:sectionEditDry,conflictChoices:{'SEC-0001':'import'}});const sectionEdited=await dx.applySafeMerge({rootData:base,envelope:sectionEdit,plan:sectionEditPlan,dryRun:sectionEditDry});assert.equal(sectionEdited.nextRootData.chapters[0].sections[0].title,'Edited Section');assert.equal(sectionEdited.nextRootData.chapters[0].sections[0].scenes[0].dialogues[0].text,'Hello');

 const brokenParent=clone(sectionAdd);brokenParent.datasets.story_sections[0].chapter_id='CHP-9999';brokenParent.metadata.package_hash='';const brokenParentDry=await dx.dryRunImport({rootData:base,envelope:brokenParent});assert.equal(brokenParentDry.summary.broken_reference,1);assert.equal(brokenParentDry.can_apply,false);
 const reparent=clone(sectionExport);reparent.datasets.story_sections[0].chapter_id='CHP-9999';reparent.metadata.package_hash='';const reparentDry=await dx.dryRunImport({rootData:base,envelope:reparent});assert(reparentDry.summary.invalid>=1);assert.equal(reparentDry.can_apply,false);
 console.log('DE-20 Story vertical gate: PASS (chapter + nested partial)');
}
main().catch(e=>{console.error(e);process.exit(1)});
